name: publish to npm
# manually run this action using the GitHub UI
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on: workflow_dispatch
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: ⎔ Setup node
              # sets up the .npmrc file to publish to npm
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'

            - name: Configure git user
              run: |
                  git config --global user.email ${{ github.actor }}@users.noreply.github.com
                  git config --global user.name ${{ github.actor }}

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
