name: Compare Snapshots
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    getMatrix:
        name: Get Matrix
        runs-on: ubuntu-24.04
        outputs:
            locale: ${{ steps.setSnapshotScope.outputs.locale }}
            version: ${{ steps.setSnapshotScope.outputs.version }}
            testPathPatterns: ${{ steps.setTestPathPatterns.outputs.testPathPatterns }}
            testConfigs: ${{ steps.setTestConfigs.outputs.testConfigs }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - id: setSnapshotScope
              name: Set snapshot scope
              run: |
                  bash ./.github/scripts/getSnapshotScope.sh
              env:
                  SNAPSHOT_BRANCH: ${{ github.head_ref || github.ref_name }}

            - id: setTestPathPatterns
              name: Set test path patterns
              run: |
                  echo "testPathPatterns=$(./.github/scripts/getTestPathPatterns.sh)" >> $GITHUB_OUTPUT
              env:
                  SNAPSHOT_LOCALE: ${{ steps.setSnapshotScope.outputs.locale }}

            - id: setTestConfigs
              name: Set test config environment variables
              run: |
                  echo "testConfigs=$(./.github/scripts/getTestConfigs.sh)" >> $GITHUB_OUTPUT
              env:
                  SNAPSHOT_LOCALE: ${{ steps.setSnapshotScope.outputs.locale }}

    compareSnapshots:
        name: Compare
        if: needs.getMatrix.outputs.testPathPatterns != '[]' && needs.getMatrix.outputs.version != 'v2'
        runs-on: ubuntu-24.04
        needs: getMatrix
        strategy:
            fail-fast: false
            matrix:
                testPathPattern: ${{ fromJSON(needs.getMatrix.outputs.testPathPatterns) }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare Snapshots - ${{ matrix.testPathPattern }}
              run: |
                  npm run test:func -- --testPathPattern "${{ matrix.testPathPattern }}"

            # - name: Collect Diffs and Upload to Imgur
            #   run: |
            #       ./scripts/snapshot-tests/collect-diffs.sh

    compareSnapshotsV2:
        name: Compare V2
        if: needs.getMatrix.outputs.testConfigs != '[]' && needs.getMatrix.outputs.version != 'v1'
        runs-on: ubuntu-24.04
        needs: getMatrix
        strategy:
            fail-fast: false
            matrix:
                testConfig: ${{ fromJSON(needs.getMatrix.outputs.testConfigs) }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServerV2.sh

            - name: Compare Snapshots - ${{ matrix.testConfig }}
              run: |
                  CONFIG_PATH=${{ matrix.testConfig }} npm run test:func:snapshots

            # - name: Collect Diffs and Upload to Imgur
            #   run: |
            #       ./scripts/snapshot-tests/collect-diffs-v2.sh
