export default [
    'DEV000ENCAPLQ',
    'DEV00ENCAPLNQ',
    'DEV00ENCAPLNA',
    'DEV000FRCAPLQ',
    'DEV00FRCAPLNQ',
    'DEV00FRCAPLNA',
    'DEV00ENCAPLTQ',
    'DEV0ENCAPLTNQ',
    'DEV00FRCAPLTQ',
    'DEV0FRCAPLTNQ',
    'DEVENCAGENRIC',
    'DEVFRCAGENRIC'
];
